namespace OpenSteamToolGUI.Core;

public static class LanguageService
{
    public static readonly (string Code, string Name)[] Languages =
    [
        ("en", "English"), ("tr", "Türkçe"), ("de", "Deutsch"), ("fr", "Français"),
        ("es", "Español"), ("pt-BR", "Português (Brasil)"), ("ru", "Русский"),
        ("zh-CN", "简体中文"), ("ja", "日本語"), ("ko", "한국어")
    ];
    private static readonly string[] Keys = ["Dashboard", "Library", "Import", "OpenSteamTool Settings", "Backups", "Diagnostics", "App Settings", "Choose Steam Folder", "Check Latest Release", "Install / Update", "Repair", "Install Debug", "Refresh", "Enable / Disable", "Edit Lua", "Choose ZIP", "Import Selected", "Replace Selected", "Keep Existing", "Save Settings", "Edit Raw TOML", "Reload", "Restore Selected", "Run Diagnostics", "Open Logs", "Uninstall OpenSteamTool"];
    private static readonly Dictionary<string, string[]> Translation = new()
    {
        ["tr"] = ["Genel Bakış", "Oyunlar", "İçe Aktar", "OpenSteamTool Ayarları", "Yedekler", "Tanılama", "Uygulama Ayarları", "Steam Klasörünü Seç", "Son Sürümü Kontrol Et", "Kur / Güncelle", "Onar", "Debug Kur", "Yenile", "Aktif / Pasif", "Lua Düzenle", "ZIP Seç", "Seçilenleri İçe Aktar", "Seçilenleri Değiştir", "Mevcutları Koru", "Ayarları Kaydet", "Ham TOML Düzenle", "Yeniden Yükle", "Seçileni Geri Yükle", "Tanılama Çalıştır", "Logları Aç", "OpenSteamTool'u Kaldır"],
        ["de"] = ["Übersicht", "Bibliothek", "Import", "OpenSteamTool Einstellungen", "Sicherungen", "Diagnose", "App Einstellungen", "Steam Ordner wählen", "Neueste Version prüfen", "Installieren / Aktualisieren", "Reparieren", "Debug installieren", "Aktualisieren", "Aktivieren / Deaktivieren", "Lua bearbeiten", "ZIP auswählen", "Auswahl importieren", "Auswahl ersetzen", "Bestehende behalten", "Einstellungen speichern", "TOML bearbeiten", "Neu laden", "Auswahl wiederherstellen", "Diagnose starten", "Logs öffnen", "OpenSteamTool deinstallieren"],
        ["fr"] = ["Tableau de bord", "Bibliothèque", "Importer", "Paramètres OpenSteamTool", "Sauvegardes", "Diagnostic", "Paramètres", "Choisir le dossier Steam", "Vérifier la version", "Installer / Mettre à jour", "Réparer", "Installer Debug", "Actualiser", "Activer / Désactiver", "Modifier Lua", "Choisir ZIP", "Importer la sélection", "Remplacer la sélection", "Garder les fichiers", "Enregistrer", "Modifier TOML", "Recharger", "Restaurer", "Lancer le diagnostic", "Ouvrir les journaux", "Désinstaller OpenSteamTool"],
        ["es"] = ["Panel", "Biblioteca", "Importar", "Ajustes de OpenSteamTool", "Copias de seguridad", "Diagnóstico", "Ajustes", "Elegir carpeta de Steam", "Buscar última versión", "Instalar / Actualizar", "Reparar", "Instalar Debug", "Actualizar", "Activar / Desactivar", "Editar Lua", "Elegir ZIP", "Importar selección", "Reemplazar selección", "Conservar existentes", "Guardar ajustes", "Editar TOML", "Recargar", "Restaurar selección", "Ejecutar diagnóstico", "Abrir registros", "Desinstalar OpenSteamTool"],
        ["pt-BR"] = ["Painel", "Biblioteca", "Importar", "Configurações OpenSteamTool", "Backups", "Diagnóstico", "Configurações", "Escolher pasta Steam", "Verificar versão", "Instalar / Atualizar", "Reparar", "Instalar Debug", "Atualizar", "Ativar / Desativar", "Editar Lua", "Escolher ZIP", "Importar seleção", "Substituir seleção", "Manter existentes", "Salvar configurações", "Editar TOML", "Recarregar", "Restaurar seleção", "Executar diagnóstico", "Abrir logs", "Desinstalar OpenSteamTool"],
        ["ru"] = ["Обзор", "Библиотека", "Импорт", "Настройки OpenSteamTool", "Резервные копии", "Диагностика", "Настройки", "Выбрать папку Steam", "Проверить версию", "Установить / Обновить", "Восстановить", "Установить Debug", "Обновить", "Включить / Отключить", "Изменить Lua", "Выбрать ZIP", "Импортировать", "Заменить", "Сохранить существующие", "Сохранить настройки", "Изменить TOML", "Перезагрузить", "Восстановить", "Диагностика", "Открыть журналы", "Удалить OpenSteamTool"],
        ["zh-CN"] = ["概览", "游戏库", "导入", "OpenSteamTool 设置", "备份", "诊断", "应用设置", "选择 Steam 文件夹", "检查最新版本", "安装 / 更新", "修复", "安装调试版", "刷新", "启用 / 禁用", "编辑 Lua", "选择 ZIP", "导入所选", "替换所选", "保留现有", "保存设置", "编辑 TOML", "重新加载", "恢复所选", "运行诊断", "打开日志", "卸载 OpenSteamTool"],
        ["ja"] = ["ダッシュボード", "ライブラリ", "インポート", "OpenSteamTool 設定", "バックアップ", "診断", "アプリ設定", "Steam フォルダーを選択", "最新版を確認", "インストール / 更新", "修復", "Debug 版", "更新", "有効 / 無効", "Lua 編集", "ZIP を選択", "選択をインポート", "選択を置換", "既存を保持", "設定を保存", "TOML 編集", "再読み込み", "選択を復元", "診断を実行", "ログを開く", "OpenSteamTool を削除"],
        ["ko"] = ["대시보드", "라이브러리", "가져오기", "OpenSteamTool 설정", "백업", "진단", "앱 설정", "Steam 폴더 선택", "최신 버전 확인", "설치 / 업데이트", "복구", "Debug 설치", "새로고침", "활성화 / 비활성화", "Lua 편집", "ZIP 선택", "선택 항목 가져오기", "선택 항목 교체", "기존 파일 유지", "설정 저장", "TOML 편집", "다시 불러오기", "선택 항목 복원", "진단 실행", "로그 열기", "OpenSteamTool 제거"]
    };
    private static readonly string[] ExtraKeys = "Logging|Manifest provider|DNS timeout (ms)|Connect timeout (ms)|Send timeout (ms)|Receive timeout (ms)|Additional Lua paths (TOML array)|Process injection|Enabled|x64 library|x86 library|Metadata mirror URL template|Use stats API|Use CloudRedirect|Appearance|Language|Check for updates on launch|Backup retention (records)|Game / Package|App IDs|State|File|Game|Confidence|Type|Source|Target|Action|Date (UTC)|Operation|ID|Add|Select All|Select None|Assign AppID".Split('|');
    private static readonly Dictionary<string, string[]> Extra = new()
    {
        ["tr"] = "Günlükleme|Manifest sağlayıcısı|DNS zaman aşımı (ms)|Bağlantı zaman aşımı (ms)|Gönderme zaman aşımı (ms)|Alma zaman aşımı (ms)|Ek Lua yolları (TOML dizisi)|İşlem enjeksiyonu|Etkin|x64 kitaplığı|x86 kitaplığı|Meta veri yansısı URL şablonu|İstatistik API'sini kullan|CloudRedirect kullan|Görünüm|Dil|Başlangıçta güncellemeleri denetle|Yedek saklama (kayıt)|Oyun / Paket|Uygulama ID'leri|Durum|Dosya|Oyun|Güven düzeyi|Tür|Kaynak|Hedef|İşlem|Tarih (UTC)|İşlem|ID|Ekle|Tümünü Seç|Seçimi Kaldır|AppID Ata".Split('|'),
        ["de"] = "Protokollierung|Manifest-Anbieter|DNS-Timeout (ms)|Verbindungs-Timeout (ms)|Sende-Timeout (ms)|Empfangs-Timeout (ms)|Zusätzliche Lua-Pfade (TOML-Array)|Prozessinjektion|Aktiviert|x64-Bibliothek|x86-Bibliothek|Metadaten-Spiegel URL-Vorlage|Statistik-API verwenden|CloudRedirect verwenden|Darstellung|Sprache|Beim Start nach Updates suchen|Sicherungen aufbewahren|Spiel / Paket|App-IDs|Status|Datei|Spiel|Sicherheit|Typ|Quelle|Ziel|Aktion|Datum (UTC)|Vorgang|ID|Hinzufügen|Alle auswählen|Keine auswählen|AppID zuweisen".Split('|'),
        ["fr"] = "Journalisation|Fournisseur de manifestes|Délai DNS (ms)|Délai de connexion (ms)|Délai d'envoi (ms)|Délai de réception (ms)|Chemins Lua supplémentaires (tableau TOML)|Injection de processus|Activé|Bibliothèque x64|Bibliothèque x86|Modèle d'URL du miroir|Utiliser l'API de statistiques|Utiliser CloudRedirect|Apparence|Langue|Chercher les mises à jour au démarrage|Conservation des sauvegardes|Jeu / Paquet|ID d'applications|État|Fichier|Jeu|Confiance|Type|Source|Destination|Action|Date (UTC)|Opération|ID|Ajouter|Tout sélectionner|Tout désélectionner|Attribuer AppID".Split('|'),
        ["es"] = "Registro|Proveedor de manifiestos|Tiempo DNS (ms)|Tiempo de conexión (ms)|Tiempo de envío (ms)|Tiempo de recepción (ms)|Rutas Lua adicionales (matriz TOML)|Inyección de procesos|Activado|Biblioteca x64|Biblioteca x86|Plantilla URL del espejo|Usar API de estadísticas|Usar CloudRedirect|Apariencia|Idioma|Buscar actualizaciones al iniciar|Conservar copias|Juego / Paquete|ID de aplicación|Estado|Archivo|Juego|Confianza|Tipo|Origen|Destino|Acción|Fecha (UTC)|Operación|ID|Añadir|Seleccionar todo|Deseleccionar todo|Asignar AppID".Split('|'),
        ["pt-BR"] = "Logs|Provedor de manifestos|Tempo limite DNS (ms)|Tempo de conexão (ms)|Tempo de envio (ms)|Tempo de recebimento (ms)|Caminhos Lua extras (lista TOML)|Injeção de processo|Ativado|Biblioteca x64|Biblioteca x86|Modelo URL do espelho|Usar API de estatísticas|Usar CloudRedirect|Aparência|Idioma|Verificar atualizações ao iniciar|Retenção de backups|Jogo / Pacote|IDs de aplicativos|Estado|Arquivo|Jogo|Confiança|Tipo|Origem|Destino|Ação|Data (UTC)|Operação|ID|Adicionar|Selecionar tudo|Limpar seleção|Atribuir AppID".Split('|'),
        ["ru"] = "Журналирование|Источник манифестов|Тайм-аут DNS (мс)|Тайм-аут подключения (мс)|Тайм-аут отправки (мс)|Тайм-аут получения (мс)|Дополнительные пути Lua (массив TOML)|Внедрение в процесс|Включено|Библиотека x64|Библиотека x86|Шаблон URL зеркала|Использовать API статистики|Использовать CloudRedirect|Внешний вид|Язык|Проверять обновления при запуске|Хранение резервных копий|Игра / Пакет|ID приложений|Состояние|Файл|Игра|Надёжность|Тип|Источник|Назначение|Действие|Дата (UTC)|Операция|ID|Добавить|Выбрать все|Снять выбор|Назначить AppID".Split('|'),
        ["zh-CN"] = "日志|清单提供方|DNS 超时（毫秒）|连接超时（毫秒）|发送超时（毫秒）|接收超时（毫秒）|额外 Lua 路径（TOML 数组）|进程注入|启用|x64 库|x86 库|元数据镜像 URL 模板|使用统计 API|使用 CloudRedirect|外观|语言|启动时检查更新|备份保留数量|游戏 / 包|应用 ID|状态|文件|游戏|可信度|类型|来源|目标|操作|日期（UTC）|操作|ID|添加|全选|全不选|指定 AppID".Split('|'),
        ["ja"] = "ログ|マニフェスト提供元|DNS タイムアウト (ms)|接続タイムアウト (ms)|送信タイムアウト (ms)|受信タイムアウト (ms)|追加 Lua パス (TOML 配列)|プロセス注入|有効|x64 ライブラリ|x86 ライブラリ|メタデータミラー URL|統計 API を使用|CloudRedirect を使用|外観|言語|起動時に更新を確認|バックアップ保持数|ゲーム / パッケージ|アプリ ID|状態|ファイル|ゲーム|信頼度|種類|元|保存先|操作|日時 (UTC)|操作|ID|追加|すべて選択|選択解除|AppID を割り当て".Split('|'),
        ["ko"] = "로그|매니페스트 공급자|DNS 제한 시간(ms)|연결 제한 시간(ms)|전송 제한 시간(ms)|수신 제한 시간(ms)|추가 Lua 경로(TOML 배열)|프로세스 주입|사용|x64 라이브러리|x86 라이브러리|메타데이터 미러 URL|통계 API 사용|CloudRedirect 사용|모양|언어|시작 시 업데이트 확인|백업 보관 수|게임 / 패키지|앱 ID|상태|파일|게임|신뢰도|유형|원본|대상|작업|날짜(UTC)|작업|ID|추가|모두 선택|모두 해제|AppID 지정".Split('|')
    };
    public static bool IsTranslatable(string english) => Array.IndexOf(ExtraKeys, english) >= 0 || UiText.Contains(english);
    public static string T(string language, string english)
    {
        if (language == "tr" && UiText.Contains(english)) return UiText.Translate(language, english);
        if (english == "Start Steam") return language switch { "de" => "Steam starten", "fr" => "Démarrer Steam", "es" => "Iniciar Steam", "pt-BR" => "Iniciar Steam", "ru" => "Запустить Steam", "zh-CN" => "启动 Steam", "ja" => "Steam を起動", "ko" => "Steam 시작", _ => english };
        if (english == "Restart Steam") return language switch { "de" => "Steam neu starten", "fr" => "Redémarrer Steam", "es" => "Reiniciar Steam", "pt-BR" => "Reiniciar Steam", "ru" => "Перезапустить Steam", "zh-CN" => "重启 Steam", "ja" => "Steam を再起動", "ko" => "Steam 다시 시작", _ => english };
        if (english == "Add Game") return language switch { "tr" => "Oyun Ekle", "de" => "Spiel hinzufügen", "fr" => "Ajouter un jeu", "es" => "Añadir juego", "pt-BR" => "Adicionar jogo", "ru" => "Добавить игру", "zh-CN" => "添加游戏", "ja" => "ゲームを追加", "ko" => "게임 추가", _ => english };
        int extra = Array.IndexOf(ExtraKeys, english);
        if (extra >= 0 && Extra.TryGetValue(language, out var translated) && extra < translated.Length) return translated[extra];
        int index = Array.IndexOf(Keys, english);
        return index >= 0 && Translation.TryGetValue(language, out var values) && index < values.Length ? values[index] : english;
    }
}
